image: alpine/edge
packages:
  - go
  # Required by codecov
  - bash
  - findutils
sources:
  - https://github.com/emersion/go-imap
tasks:
  - build: |
      cd go-imap
      go build -v ./...
  - lint: |
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
      cd go-imap
      $(go env GOPATH)/bin/golangci-lint run ./... || true
  - test: |
      cd go-imap
      go test -coverprofile=coverage.txt -covermode=atomic ./...
  - upload-coverage: |
      cd go-imap
      export CODECOV_TOKEN=8c0f7014-fcfa-4ed9-8972-542eb5958fb3
      curl -s https://codecov.io/bash | bash
