image: alpine/edge
packages:
  - go
  # Required by codecov
  - bash
  - findutils
sources:
  - https://github.com/faziloub/go-imap
tasks:
  - build: |
      cd go-imap
      go build -v ./...
  - test: |
      cd go-imap
      go test -coverprofile=coverage.txt -covermode=atomic ./...
  - upload-coverage: |
      cd go-imap
      export CODECOV_TOKEN=8c0f7014-fcfa-4ed9-8972-542eb5958fb3
      curl -s https://codecov.io/bash | bash
